### ISSUE TITLE
I don't understand the documentation

### ISSUE THREAD

**Issue by marvindanig** [follmann/favicon_maker#18]
I included gem 'favicon_maker' on my Gemfile, what do I do next? Where does the code block with 'FaviconMaker.generate' go and how to include the generated icons in the layout?

**Comment by follmann** [comment]
Well it depends. This gem has a sister project called [middleman-favicon-maker](https://github.com/follmann/middleman-favicon-maker) that effortlessly integrates with the Middleman framework, that I developed it for. If you use Rails you'd probably go the route of either generating the icons via a rake task, therefore placing the generate block in there. Or you make the icon generation part of your deployment script. Here is an example from the old instructions (only meant to jump start you), it is untested and probably not up-to-date: https://github.com/follmann/favicon_maker/blob/master/OLD_INSTRUCTIONS.md

Regarding including the icons in your layout. You don't have to do that per se. But if you want, this will help you: https://github.com/follmann/middleman-favicon-maker#markup-meta-links

**Comment by marvindanig** [comment]
Hey follman, thanks for your answer! I've this rails app that's going to have a _logo_ that's not gonna change over time. So I guess a rake task would be enough I wouldn't need it on my deploy script. I'm not using middleman but I'm hoping that this gem will work without it.

I was quite shocked when I learned that we don't need to add each of the icon_sizes individually on our layout because iOS takes care of it automatically; but then we also have a bulk of world on Android/others too. So no donut for web developers :( 

Thanks, let me try the gem and come back on another thread if I need help.
