### ISSUE TITLE
Create favicons for uploaded image

### ISSUE THREAD

**Issue by kavitakanojiya** [follmann/favicon_maker#19]
Hey @follmann ,

I am trying to create favicons for an uploaded image that is saved on AWS S3. Is it possible to generate favicons from uploaded image. Once these favicons are generated, I would like to host them on S3. 

The requirement is we have subdomain feature in one of our app. Each subdomain will have their branded image, out of which we need to create favicons and hook them up to HEAD tag.

Now, I see this gem expects folder directories. Is there a way to pass live site URL ?

Thanks.

**Comment by follmann** [comment]
Hi @kavitakanojiya 

while ImageMagick (which is used for the actual image operations) is generally able to deal with input via an URL, FaviconMaker isn't as of now. I'm afraid I won't be able to add support for it anytime soon. If you want to take a stab at it, I would be happy to include a PR. You could extend the DSL to allow `from_url` to signal a remote file as input.

Cheers!
