### ISSUE TITLE
Wrong version displayed in warning message

### ISSUE THREAD

**Issue by Tuckie** [follmann/favicon_maker#22]
[This](https://github.com/follmann/favicon_maker/blob/43279e0419eef2d5b185815cdf09edde60629af1/lib/favicon_maker/creator.rb#L82) should be using `im_version` instead of `RECENT_IM_VERSION` (along with some way to pass/access `im_version`)

**Comment by follmann** [comment]
You're absolutely right! Will fix soon...

**Comment by follmann** [comment]
Fixed in gem version 1.3.1

**Comment by Tuckie** [comment]
Thanks!
